# Generated by Django 5.0.6 on 2024-05-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['-id'], 'verbose_name': 'Info', 'verbose_name_plural': 'Infos'},
        ),
    ]
