# Generated by Django 5.0.6 on 2024-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_category',
            field=models.ManyToManyField(blank=True, related_name='articles', to='app_article.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_reviews',
            field=models.ManyToManyField(blank=True, related_name='articles', to='app_article.review'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
