# Generated by Django 5.0.6 on 2024-05-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0003_keywords_article_art_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='art_annotations',
            new_name='art_annotations_uz',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='art_full_text',
            new_name='art_full_text_uz',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='art_title',
            new_name='art_title_uz',
        ),
    ]
