# Generated by Django 5.0.6 on 2024-05-17 17:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0004_rename_art_annotations_article_art_annotations_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_annotations_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='art_full_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='art_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
