# Generated by Django 5.0.6 on 2024-05-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0006_article_art_journal_article_art_status'),
        ('app_journal', '0002_rename_journal_file_journal_journal_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app_journal.journal'),
        ),
    ]
