# Generated by Django 5.0.6 on 2024-05-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0007_alter_article_art_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
