# Generated by Django 5.0.6 on 2024-05-18 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_datetime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_description', models.CharField(max_length=255)),
                ('jornal_logo', models.FileField(upload_to='journal_logo/%Y/%m/%d')),
                ('Journal_file', models.FileField(upload_to='journal_files/%Y/%m/%d')),
                ('jornal_datetime', models.DateTimeField(auto_now_add=True)),
                ('jornal_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jornal_tags', models.ManyToManyField(blank=True, to='app_journal.tags')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journal',
                'db_table': 'journal',
            },
        ),
    ]
