# Generated by Django 5.0.6 on 2024-05-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='Journal_file',
            new_name='journal_file',
        ),
    ]
