# Generated by Django 5.0.6 on 2024-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0002_rename_journal_file_journal_journal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='jornal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
