# Generated by Django 5.0.6 on 2024-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_journal', '0003_journal_jornal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='jornal_name',
            field=models.CharField(max_length=255),
        ),
    ]
